package proxy

const (
	REQUEST_LOGGER_EMMIT   = "REQUEST_LOGGER_EMMIT"
	DEFAULT_VERSION        = "1"
	GOWAY_PRODUCT          = "GOWAY-PRODUCT"
	GOWAY_CLIENT           = "GOWAY-CLIENT"
	GOWAY_VERSION          = "GOWAY-VERSION"
	API_ROUTE_NOT_FOUND    = "API_ROUTE_NOT_FOUND"
	ROUTE_NOT_FOUND        = "ROUTE_NOT_FOUND"
	AUTHENTICATION_HANDLER = "AUTHENTICATION"
	CUSTOM_HANDLER         = "HANDLER_ERROR"
	API_KEY_NOT_FOUND      = "API_KEY_NOT_FOUND"
	GOWAY_BASE_PATH        = "GOWAY_BASE_PATH"
	GOWAY_SERVICE_NAME     = "GOWAY_SERVICE_NAME"
	WHERE_HEADER           = "header"
	WHERE_PARAMS           = "params"
	WHERE_URL              = "url"
)
